repos:
  - repo: local
    hooks:
      # Code formatting
      - id: ruff-check
        name: Ruff Check
        stages:
          - pre-commit
        language: system
        entry: poetry run ruff check --fix
        types:
          - python

      - id: ruff-format
        name: Ruff Format
        stages:
          - pre-commit
        language: system
        entry: poetry run ruff format
        types:
          - python

      # Code analysis
      - id: mypy
        name: MyPy
        stages:
          - pre-commit
        language: system
        entry: poetry run mypy
        types:
          - python
        pass_filenames: false

      # Tests
      - id: pytest
        name: Pytest
        stages:
          - pre-commit
        language: system
        entry: poetry run pytest
        types:
          - python
        pass_filenames: false
