repos:
  - repo: local
    hooks:
      # Code formatting
      - id: ruff-check
        name: Ruff Check
        stages:
          - pre-commit
        language: python
        entry: ruff check --fix
        types:
          - python
      - id: ruff-format
        name: Ruff Format
        stages:
          - pre-commit
        language: python
        entry: ruff format
        types:
          - python

      # Code analysis
      - id: mypy
        name: MyPy
        stages:
          - pre-commit
        language: python
        entry: mypy
        types:
          - python
        pass_filenames: false
