repos:
  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        stages: [commit]
        language: system
        types: [python]
        entry: autoflake
        args: [--in-place, --recursive, --remove-unused-variables, --remove-all-unused-imports]

      - id: isort
        name: isort
        stages: [commit]
        language: system
        types: [python]
        entry: isort

      - id: black
        name: black
        stages: [commit]
        language: system
        types: [python]
        entry: black
