name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  checks:
    name: Checks (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install Poetry
        run: pipx install poetry==2.4.1
      - uses: actions/setup-python@v7
        with:
          python-version: "3.14"
          cache: poetry
      - name: Install dependencies
        run: poetry install
      - name: Lint
        run: poetry run ruff check
      - name: Check formatting
        run: poetry run ruff format --check
      - name: Check types
        run: poetry run mypy
      - name: Test
        run: poetry run pytest